// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "hQQOPOOOOOO'#C`'#C`QQOPOOOOOO-E6^-E6^",
  stateData: "Y~OQPORPO~O",
  goto: "[TPPPPUQQORRQ",
  nodeNames: "⚠ Program SQL Mustache",
  maxTerm: 5,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "%w~RUO#oe#o#p!f#p#qe#r;'Se;'S;=`!`<%lOe~jUQ~O#oe#o#p|#p#qe#r;'Se;'S;=`!`<%lOe~!PTO#oe#p#qe#r;'Se;'S;=`!`<%lOe~!cP;=`<%le~!iUO#oe#o#p!{#p#qe#r;'Se;'S;=`!`<%lOe~#O[X^!{pq!{!c!}#t#T#o#t#y#z!{$f$g!{#BY#BZ!{$IS$I_!{$I|$JO!{$JT$JU!{$KV$KW!{&FU&FV!{~#w_X^$vpq$v!O!P#t!Q![#t!c!}#t#T#o#t#q#r%l#y#z$v$f$g$v#BY#BZ$v$IS$I_$v$I|$JO$v$JT$JU$v$KV$KW$v&FU&FV$v~$yZX^$vpq$v#q#r%l#y#z$v$f$g$v#BY#BZ$v$IS$I_$v$I|$JO$v$JT$JU$v$KV$KW$v&FU&FV$v~%oP#q#r%r~%wOR~",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})

