// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "hQQOPOOOOOO'#C`'#C`QQOPOOOOOO-E6^-E6^",
  stateData: "Y~OQPORPO~O",
  goto: "[TPPPPUQQORRQ",
  nodeNames: "⚠ Program SQL Mustache",
  maxTerm: 5,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "'S~RVO#oh#o#p#R#p#qh#q#r!o#r;'Sh;'S;=`!i<%lOh~mVQ~O#oh#o#p!S#p#qh#q#r!o#r;'Sh;'S;=`!i<%lOh~!VUOrhs#oh#p#qh#r;'Sh;'S;=`!i<%lOh~!lP;=`<%lh~!rTOrhs#qh#r;'Sh;'S;=`!i<%lOh~#UVOrhs#oh#o#p#k#p#qh#r;'Sh;'S;=`!i<%lOh~#n_X^#kpq#ktu$m!c!}$m#R#S$m#T#o$m#q#r&w#y#z#k$f$g#k#BY#BZ#k$IS$I_#k$I|$JO#k$JT$JU#k$KV$KW#k&FU&FV#k~$peX^&Rpq&Rtu$mxy$myz$m!O!P$m!Q![$m!c!}$m!}#O$m#P#Q$m#R#S$m#T#o$m#q#r&w#y#z&R$f$g&R#BY#BZ&R$IS$I_&R$I|$JO&R$JT$JU&R$KV$KW&R&FU&FV&R~&UZX^&Rpq&R#q#r&w#y#z&R$f$g&R#BY#BZ&R$IS$I_&R$I|$JO&R$JT$JU&R$KV$KW&R&FU&FV&R~&zP#q#r&}~'SOR~",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})

