// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#SQQOPOOOVOPO'#C_OOOO'#C^'#C^OOOO'#Cd'#CdQQOPOOOOOO'#Ce'#CeO_OPO,58yOgOPO,58yOOOO-E6b-E6bOOOO-E6c-E6cOoOPO1G.eOoOPO1G.eOOOO1G.e1G.eOwOPO7+$POOOO7+$P7+$POOOO<<Gk<<Gk",
  stateData: "!P~OSPO~OTTOUVO~OTTOUYO~OTTOV[O~OTTOV^O~OTTOV_O~O",
  goto: "wYPPZ_PPPPciTROSTQOSQSORWSQUPUXUZ]QZVR]Y",
  nodeNames: "⚠ Program Statement TemplateExpression OpenCurly Whitespace VariablePath CloseCurly",
  maxTerm: 10,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "!{~R^X^}pq}!c!}!S#T#o!S#o#p!e#q#r!p#y#z}$f$g}#BY#BZ}$IS$I_}$I|$JO}$JT$JU}$KV$KW}&FU&FV}~!SOT~~!XSU~!O!P!S!Q![!S!c!}!S#T#o!S~!hP#o#p!k~!pOS~~!sP#q#r!v~!{OV~",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})

